version: '3.8'

services:
  authentication:
    build: ./back/authentication
    container_name: authentication
    ports:
      - "4000:4000"
    networks:
      - cesieats-network
    env_file:
      - ./back/authentication/.env
    depends_on:
      - mysql-db
      - mongo-db
    
  products:
    build: ./back/products
    container_name: products
    ports:
      - "3010:3010"
    networks:
      - cesieats-network
    env_file:
      - ./back/products/.env
    depends_on:
      - mongo-db

  menus:
    build: ./back/menus
    container_name: menus
    ports:
      - "3020:3020"
    networks:
      - cesieats-network
    env_file:
      - ./back/menus/.env
    depends_on:
      - mongo-db

  orders:
    build: ./back/orders
    container_name: orders
    ports:
      - "3030:3030"
    networks:
      - cesieats-network
    env_file:
      - ./back/orders/.env
    depends_on:
      - mongo-db 

  deliveries:
    build: ./back/deliveries
    container_name: deliveries
    ports:
      - "3040:3040"
    networks:
      - cesieats-network
    env_file:
      - ./back/deliveries/.env
    depends_on:
      - mongo-db

  restaurants:
    build: ./back/restaurants
    container_name: restaurants
    ports:
      - "3050:3050"
    networks:
      - cesieats-network
    env_file:
      - ./back/restaurants/.env
    depends_on:
      - mongo-db

  mysql-db:
    image: mysql:9
    container_name: mysql-db
    ports:
      - "3306:3306"
    networks:
      - cesieats-network
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  mongo-db:
    image: mongo:7
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cesieats-network

  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - cesieats-network
    depends_on:
      - authentication
      - menus
      - products
      - orders
      - deliveries
      - restaurants

networks:
  cesieats-network:

volumes:
  mysql_data:
  mongodb_data: